In [2]:
'''with open('../requirements.txt', 'w') as f:
    f.write('pandas == 2.1.3\nnumpy == 1.26.0\npsycopg2 == 2.9.3\nsqlalchemy == 2.0.23')'''

In [ ]:
# if necessary
#! pip install -r ../requirements.txt

# Movie Database
Written and executed in a jupyter notebook

<b> must run

In [7]:
import pandas as pd
import numpy as np
import psycopg2 as ps # postgresql database connection
import os # for environment variables
from sqlalchemy import create_engine # for pandas and postgresql connection
import requests # for API connection later
import json # for easier API data search later
import re # for searching text
import datetime # for gathering dates and times

In [1]:
! pwd
! ls ../CSV

/Users/carterthurman/Documents/GitHub/Movie_DB/Notebooks
final_movies.csv movies.csv       trnd_movies.csv  up_movies.csv

In [20]:
# creating paths and dest file paths 
path = '../CSV/movies.csv'
dest = '../CSV/final_movies.csv'
trnd_dest = '../CSV/trnd_movies.csv'
up_dest = '../CSV/up_movies.csv'

## Reading Data

<b> must run

In [16]:
# reading file to dataframe
df = pd.read_csv(path, index_col=0)
df

,Movie_Title,Year,Genres,Ratings,Tagline,Stars,Votes,Runtime,Gross
0,Blood Red Sky,(2021),"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri B...,21062.0,121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michel...",17870.0,25.0,NaN
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman R...",885805.0,44.0,NaN
3,Rick and Morty,(2013– ),"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Pa...",414849.0,23.0,NaN
4,Army of Thieves,(2021),"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,Add a Plot,"Stars:Morgan Taylor Campbell, ...",NaN,NaN,NaN
9995,Arcane,(2021– ),"Animation, Action, Adventure",NaN,Add a Plot,NaN,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"Documentary, Sport",NaN,Add a Plot,Director:Orlando von Einsiedel| Star:P...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,Add a Plot,Director:Jovanka Vuckovic| Stars:Morga...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,Add a Plot,Director:Jovanka Vuckovic| Stars:Morga...,NaN,NaN,NaN

In [17]:
# change column names
df.rename(columns=
                     {'MOVIES': 'Movie_Title'
                        ,'YEAR': 'Year'
                        ,'GENRE': 'Genres'
                        ,'RATING': 'Ratings'
                        ,'ONE-LINE': 'Tagline'
                        ,'STARS': 'Stars'
                        ,'VOTES': 'Votes'
                        ,'RunTime': 'Runtime'}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Movie_Title  9999 non-null   object
 1   Year         9355 non-null   object
 2   Genres       9919 non-null   object
 3   Ratings      8179 non-null   float64
 4   Tagline      9999 non-null   object
 5   Stars        9543 non-null   object
 6   Votes        8179 non-null   float64
 7   Runtime      7041 non-null   float64
 8   Gross        460 non-null    float64
dtypes: float64(4), object(5)
memory usage: 781.2+ KB

## Data Cleaning

In [18]:
# for each column in df_mov, check if the column is an 'object' ('O') datatype, 
# and if so, replace '\n' (newline) with empty string ''

for column in df.columns:
    if df['{}'.format(column)].dtype == 'O':
        # formating column name into the dataframe search, searching for '\n' and replacing with empty string ''
        df['{}'.format(column)] = df['{}'.format(column)].str.replace('\n', '')

# changing columns to correct datatypes after replacing specific characters

#df['Votes'] = df['Votes'].str.replace(',','')
df['Votes'] = df['Votes'].astype('float64')
#df['Gross'] = df['Gross'].str.replace('$','').str.replace('M', '')
df['Gross'] = df['Gross'].astype('float64')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Movie_Title  9999 non-null   object
 1   Year         9355 non-null   object
 2   Genres       9919 non-null   object
 3   Ratings      8179 non-null   float64
 4   Tagline      9999 non-null   object
 5   Stars        9543 non-null   object
 6   Votes        8179 non-null   float64
 7   Runtime      7041 non-null   float64
 8   Gross        460 non-null    float64
dtypes: float64(4), object(5)
memory usage: 781.2+ KB

In [20]:
# cleaning up

# Grabs the first Genre and puts it into a new column based on ','
df['Main_Genre'] = df['Genres'].str.split(',', expand=True)[0]

# grabs first four digits (the year made) and puts it into a new column
df['Main_Year'] = df['Year'].str.extract(r'(\d{4})', expand=True)

# changing year to Int64 type for better aggregation
df['Main_Year'] = df['Main_Year'].astype('Int64')

# replacing 0 with np.nan to get better results
df['Gross'] = df['Gross'].replace(0, np.nan)

# Reorganizing columns
df = df[['Movie_Title', 'Main_Year', 'Main_Genre', 'Ratings', 'Tagline', 'Stars', 'Votes', 'Runtime', 'Gross', 'Genres', 'Year']]
df.rename(columns={'Year': 'Year_Range'}, inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9998
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Movie_Title  9999 non-null   object
 1   Main_Year    9251 non-null   Int64
 2   Main_Genre   9919 non-null   object
 3   Ratings      8179 non-null   float64
 4   Tagline      9999 non-null   object
 5   Stars        9543 non-null   object
 6   Votes        8179 non-null   float64
 7   Runtime      7041 non-null   float64
 8   Gross        445 non-null    float64
 9   Genres       9919 non-null   object
 10  Year_Range   9355 non-null   object
dtypes: Int64(1), float64(4), object(6)
memory usage: 947.2+ KB

## Minor Data Searching

In [22]:
# finding top 100 movie title that contains regex string, and that DOES NOT (~) contain a specific string
# in this case we are finding a movie/TV title that contains Avatar Airbend and NOT a tagline that contains 'Live'
# so finding animated series instead of Live series

df[df['Movie_Title'].str.contains(r'Avatar.*Airbend') & ~df['Tagline'].str.contains('Live')].head(100)

,Movie_Title,Main_Year,Main_Genre,Ratings,Tagline,Stars,Votes,Runtime,Gross,Genres,Year_Range
129,Avatar: The Last Airbender,2005,Animation,9.3,"In a war-torn world of elemental magic, a youn...","Stars:Dee Bradley Baker, Zach ...",265845.0,23.0,NaN,"Animation, Action, Adventure",(2005–2008)
6475,Avatar: The Last Airbender,2005,Animation,7.6,Sokka and Katara have to solve a centuries-old...,Director:Lauren MacMullan| Stars:Zach ...,2871.0,24.0,NaN,"Animation, Action, Adventure",(2005–2008)
6476,Avatar: The Last Airbender,2005,Animation,8.7,"After getting a house to stay in, Aang and com...",Director:Lauren MacMullan| Stars:Zach ...,2857.0,25.0,NaN,"Animation, Action, Adventure",(2005–2008)
6477,Avatar: The Last Airbender,2005,Animation,8.0,"In a nearby Earth Village, the gang meets a te...",Director:Dave Filoni| Stars:Zach Tyler...,3229.0,25.0,NaN,"Animation, Action, Adventure",(2005–2008)
6478,Avatar: The Last Airbender,2005,Animation,7.8,"Aang, Katara, and Sokka have their friendship ...",Director:Dave Filoni| Stars:Zach Tyler...,3164.0,25.0,NaN,"Animation, Action, Adventure",(2005–2008)
...,...,...,...,...,...,...,...,...,...,...,...
8506,Avatar: The Last Airbender,2005,Animation,8.7,"The gang, now hiding at Ember Island, watch a ...",Director:Giancarlo Volpe| Stars:Zach T...,3246.0,25.0,NaN,"Animation, Action, Adventure",(2005–2008)
8507,Avatar: The Last Airbender,2005,Animation,9.2,Sozin's Comet is only three days away. Zuko te...,Director:Ethan Spaulding| Stars:Zach T...,3465.0,92.0,NaN,"Animation, Action, Adventure",(2005–2008)
8508,Avatar: The Last Airbender,2005,Animation,9.5,Aang awakes on a mysterious island and confron...,Director:Giancarlo Volpe| Stars:Zach T...,3845.0,92.0,NaN,"Animation, Action, Adventure",(2005–2008)
8509,Avatar: The Last Airbender,2005,Animation,9.8,Zuko battles his sister with Katara's help for...,Director:Joaquim Dos Santos| Stars:Zac...,5283.0,92.0,NaN,"Animation, Action, Adventure",(2005–2008)
8510,Avatar: The Last Airbender,2005,Animation,9.9,Aang's moment of truth arrives. Can he defeat ...,Director:Joaquim Dos Santos| Stars:Zac...,8813.0,92.0,NaN,"Animation, Action, Adventure",(2005–2008)

In [23]:
# finding unique values (won't print out, long list)
df['Gross'].unique()

# finding NA values sum, and count of non NA values
df['Gross'].isna().sum(), df['Gross'].count()

(9554, 445)

In [24]:
# grabbing median for one column (some scewed results) that aren't NA
df['Gross'].median(skipna=True)

8.55

In [25]:
# temporary dropping na values, grabbing Movie Title and Gross columns, sorting by Gross and Ascending
df[['Movie_Title', 'Gross']].dropna().sort_values(by='Gross', ascending=True)

                         Movie_Title   Gross
512            The Clovehitch Killer    0.01
6056                  Theo Who Lived    0.01
1216                       Honeymoon    0.01
4196             The Sunshine Makers    0.01
1317                     Duck Butter    0.01
...                              ...     ...
196                       Spider-Man  403.71
144   Jumanji: Welcome to the Jungle  404.52
226       Captain America: Civil War  408.08
578                     Finding Dory  486.30
329             Beauty and the Beast  504.01

[445 rows x 2 columns]

## To CSV

In [26]:
# making csv file "final_movies.csv"
df.to_csv(dest)
! ls ../CSV

ls: CSV: No such file or directory

## Getting data into PostgreSQL

In [5]:
# gathering environmental variable for the postgres db password
SQL_DB_KEY = os.environ.get('SQL_DB_KEY')
# gathering user environmental variable for postgres user id
ENV_USER = os.environ.get('USER')

In [9]:
# creating sqlachemy engine to read data from postgresql
engine = create_engine(f'postgresql+psycopg2://postgres:{SQL_DB_KEY}@localhost/{ENV_USER}')
engine

Engine(postgresql+psycopg2://postgres:***@localhost/carterthurman)

In [36]:
# 'append, replace, fail' arguments.
# index = False is 
df.to_sql('movie_table', engine, if_exists='replace', index=False)

999

## Putting data into PostgreSQL via chunks 
Alternate way, for bigger datasets

for chunk in pd.read_csv(dest, index_col=0, chunksize=1000): 
    chunk.to_sql('movie_table', engine, if_exists="replace")

## Reading Data from PostgreSQL

In [37]:
sql_df = pd.read_sql_query('SELECT * from public."movie_table"', engine)

In [38]:
sql_df

,Movie_Title,Main_Year,Main_Genre,Ratings,Tagline,Stars,Votes,Runtime,Gross,Genres,Year_Range
0,Blood Red Sky,2021.0,Action,6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri B...,21062.0,121.0,NaN,"Action, Horror, Thriller",(2021)
1,Masters of the Universe: Revelation,2021.0,Animation,5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michel...",17870.0,25.0,NaN,"Animation, Action, Adventure",(2021– )
2,The Walking Dead,2010.0,Drama,8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman R...",885805.0,44.0,NaN,"Drama, Horror, Thriller",(2010–2022)
3,Rick and Morty,2013.0,Animation,9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Pa...",414849.0,23.0,NaN,"Animation, Adventure, Comedy",(2013– )
4,Army of Thieves,2021.0,Action,NaN,"A prequel, set before the events of Army of th...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN,NaN,"Action, Crime, Horror",(2021)
...,...,...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,2021.0,Adventure,NaN,Add a Plot,"Stars:Morgan Taylor Campbell, ...",NaN,NaN,NaN,"Adventure, Drama, Fantasy",(2021– )
9995,Arcane,2021.0,Animation,NaN,Add a Plot,None,NaN,NaN,NaN,"Animation, Action, Adventure",(2021– )
9996,Heart of Invictus,2022.0,Documentary,NaN,Add a Plot,Director:Orlando von Einsiedel| Star:P...,NaN,NaN,NaN,"Documentary, Sport",(2022– )
9997,The Imperfects,2021.0,Adventure,NaN,Add a Plot,Director:Jovanka Vuckovic| Stars:Morga...,NaN,NaN,NaN,"Adventure, Drama, Fantasy",(2021– )
9998,The Imperfects,2021.0,Adventure,NaN,Add a Plot,Director:Jovanka Vuckovic| Stars:Morga...,NaN,NaN,NaN,"Adventure, Drama, Fantasy",(2021– )

# API

## movie db
https://www.themoviedb.org/settings/api/stats <BR>
https://developer.themoviedb.org/reference/trending-all

<b> must run

In [2]:
# gathering my environment keys
MDB_KEY = os.environ.get('MOVIE_DB_KEY')
RA_KEY = os.environ.get('READ_ACCESS_KEY')
ACCOUNT_KEY = os.environ.get('ACCOUNT_ID_KEY')

In [3]:
# gathering environmental variable for the postgres db password
SQL_DB_KEY = os.environ.get('SQL_DB_KEY')
# gathering user environmental variable for postgres user id
ENV_USER = os.environ.get('USER')

In [4]:
# creating sqlachemy engine to read data from postgresql
engine = create_engine(f'postgresql+psycopg2://postgres:{SQL_DB_KEY}@localhost/{ENV_USER}')
engine

Engine(postgresql+psycopg2://postgres:***@localhost/carterthurman)

In [5]:
# Testing connection

url = "https://api.themoviedb.org/3/authentication"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer {0}".format(RA_KEY)
}

response = requests.get(url, headers=headers)

print(response.text)

{"success":true,"status_code":1,"status_message":"Success."}

### Trending Movies

To iterate through pages:

url = "https://api.themoviedb.org/3/trending/movie/day?api_key=THE_KEY&page=1"

In [32]:
%%time

# this section is to create the dataframe and gather the first 20 items

# gathering Trending Movies

# specified page number
url = "https://api.themoviedb.org/3/trending/movie/day?api_key=THE_KEY&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer {}".format(RA_KEY)
}

response_trnd = requests.get(url, headers=headers)

print(response_trnd)

# decodes response into json object
json_data_trnd = response_trnd.content.decode()
# converts json object/string into python object
data_trnd = json.loads(json_data_trnd)

# gathering columns into list
trnd_columns = [i for i in data_trnd['results'][0].keys()]
# unpacking data from json object into the data argument and setting columns, making a dataframe
trnd_df = pd.DataFrame([*data_trnd['results']], columns=trnd_columns)
trnd_df

<Response [200]>
CPU times: user 53.2 ms, sys: 5.25 ms, total: 58.5 ms
Wall time: 322 ms

,adult,backdrop_path,id,title,original_language,original_title,overview,poster_path,media_type,genre_ids,popularity,release_date,video,vote_average,vote_count
0,False,/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg,753342,Napoleon,en,Napoleon,An epic that details the checkered rise and fa...,/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg,movie,"[36, 10752, 18]",1092.626,2023-11-22,False,6.445,1005
1,False,/qgFrFXtiGfWN1zkk4sPd0nwFaBF.jpg,848187,Role Play,en,Role Play,Emma has a wonderful husband and two kids in t...,/7MhXiTmTl16LwXNPbWCmqxj7UxH.jpg,movie,"[28, 35, 10749]",26.680,2023-12-14,False,6.222,9
2,False,/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg,955916,Lift,en,Lift,"An international heist crew, led by Cyrus Whit...",/paXvbaaT5kCZbCqiWrnf44tGAyn.jpg,movie,"[28, 35]",147.906,2024-01-10,False,7.200,5
3,False,/uKP0B8HUJ08fas7NF77Xwu0bolJ.jpg,1214314,One More Shot,en,One More Shot,Following the attack on the black site in Pola...,/gdF3Q1Mcr2XvxLPStQSoQIO2cIj.jpg,movie,"[28, 53]",38.525,2024-01-12,False,7.306,18
4,False,/rVJfabCz1ViynQCEz54MRqdZig1.jpg,1155089,Justice League: Crisis on Infinite Earths Part...,en,Justice League: Crisis on Infinite Earths Part...,Death is coming. Worse than death: oblivion. N...,/zR6C66EDklgTPLHRSmmMt5878MR.jpg,movie,"[16, 878, 28]",104.182,2024-01-09,False,7.900,53
5,False,/vdpE5pjJVql5aD6pnzRqlFmgxXf.jpg,906126,Society of the Snow,es,La sociedad de la nieve,"On October 13, 1972, Uruguayan Air Force Fligh...",/2e853FDVSIso600RqAMunPxiZjq.jpg,movie,"[18, 36]",1412.999,2023-12-13,False,8.085,595
6,False,/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg,866398,The Beekeeper,en,The Beekeeper,One man’s campaign for vengeance takes on nati...,/A7EByudX0eOzlkQ2FIbogzyazm2.jpg,movie,"[28, 53]",453.101,2024-01-10,False,7.520,25
7,False,/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg,872585,Oppenheimer,en,Oppenheimer,The story of J. Robert Oppenheimer's role in t...,/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg,movie,"[18, 36]",674.156,2023-07-19,False,8.115,6049
8,False,/nHf61UzkfFno5X1ofIhugCPus2R.jpg,346698,Barbie,en,Barbie,Barbie and Ken are having the time of their li...,/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg,movie,"[35, 12, 14]",399.454,2023-07-19,False,7.146,6866
9,False,/plLqCMIYgvh3dqnIm16da7lDtmb.jpg,1072876,Self Reliance,en,Self Reliance,When a man is offered a million dollars to pla...,/4AH3S0xMEYW20KGI6CSPO1W70bo.jpg,movie,[35],16.292,2024-01-03,False,4.300,3
10,False,/m3s0jyPGtluJ48kD0fUiPjXrRhr.jpg,673593,Mean Girls,en,Mean Girls,New student Cady Heron is welcomed into the to...,/fbbj3viSUDEGT1fFFMNpHP1iUjw.jpg,movie,[35],202.390,2024-01-10,False,6.848,23
11,False,/vrpSBM5Zr2L15cFKhOwlKA8Ttyc.jpg,1211957,The Painter,en,The Painter,An ex-CIA operative is thrown back into a dang...,/gqzlmjyBej9EJXuB6IsIT9LWqvV.jpg,movie,"[28, 53]",13.202,2024-01-05,False,6.700,3
12,False,/mSJ18SvWHShacTp8BcqH5WRCkGQ.jpg,927107,The Bricklayer,en,The Bricklayer,Someone is blackmailing the CIA by assassinati...,/pwOQ9lqLX1OgsJRSybS662wMcu8.jpg,movie,"[28, 53]",203.920,2023-12-14,False,6.500,30
13,False,/rrfBenawPGhkt5yvb124NSZwnAC.jpg,930564,Saltburn,en,Saltburn,Struggling to find his place at Oxford Univers...,/qjhahNLSZ705B5JP92YMEYPocPz.jpg,movie,"[18, 35, 53]",478.032,2023-11-16,False,7.137,1017
14,False,/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg,572802,Aquaman and the Lost Kingdom,en,Aquaman and the Lost Kingdom,"Black Manta, still driven by the need to aveng...",/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg,movie,"[28, 12, 14]",1117.610,2023-12-20,False,6.500,458
15,False,/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg,695721,The Hunger Games: The Ballad of Songbirds & Sn...,en,The Hunger Games: The Ballad of Songbirds & Sn...,64 years before he becomes the tyrannical pres...,/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg,movie,"[18, 878, 28]",753.390,2023-11-15,False,7.229,1435
16,False,/sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg,840430,The Holdovers,en,The Holdovers,A curmudgeonly instructor at a New England pre...,/VHSzNBTwxV8vh7wylo7O9CLdac.jpg,movie,"[35, 18]",123.842,2023-10-27,False,7.660,331
17,False,/gsVC7HMf4VR2XFOyqjTSklY2Tms.jpg,792307,Poor Things,en,Poor Things,Brought back to life by an unorthodox scientis...,/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg,movie,"[878, 10749, 35]",170.340,2023-11-21,False,8.017,87
18,False,/1X7vow16X7CnCoexXh4H4F2yDJv.jpg,466420,Killers of the Flower Moon,en,Killers of the Flower Moon,When oil is discovered in 1920s Oklahoma under...,/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg,movie,"[80, 18, 36]",394.389,2023-10-18,False,7.524,1830
19,False,/sRLC052ieEzkQs9dEtPMfFxYkej.jpg,848326,Rebel Moon - Part One: A Child of Fire,en,Rebel Moon - Part One: A Child of Fire,When a peaceful colony on the edge of the gala...,/ui4DrH1cKk2vkHshcUcGt2lKxCm.jpg,movie,"[878, 18, 28]",658.059,2023-12-15,False,6.451,1181

In [33]:
%%time

# gathers the total pages of response
match = re.search(r'"total_pages":(\d{4})', response_trnd.text)
print(match)
# if the response gave a correct variable and not an error, it will grab the page number by the first group
# else, it will print "Number not found"
if match:
    page_number = match.group(1)
    print(f"Number: {page_number}")
else:
    print("Number not found")

# converting page_nunber into 'int' variable
page_number = int(page_number)
    
# gathering Trending Movies one page at a time through iteration
# this whole block of code with try to do it and until it fails, it will continue. 
# once it fails, it will print "Out of Pages"

# this block of code takes around 30 seconds to run.
try:
    # for each page starting at page 2 (because we already have page 1), iterate through and gather the response
    # including the url which the page_number is being formatted into, the headers with the environmental keys
    # and then putting it into a response variable which is then being decoded into a json object
    # and then loading into a data_trnd json object that can be searched through
    
    for page in range(2, page_number):
        url = f"https://api.themoviedb.org/3/trending/movie/day?api_key=THE_KEY&page={page}"
        headers = {
            "accept": "application/json",
            "Authorization": "Bearer {}".format(RA_KEY)}
        response_trnd = requests.get(url, headers=headers)
        # decodes response into json object
        json_data_trnd = response_trnd.content.decode()
        # converts json object/string into python object
        data_trnd = json.loads(json_data_trnd)
        # if data_trnd exists, then add it to a temporary dataframe with correct columns, and then 
        # join it (concat it) into the already created dataframe while ignoring the index column.
        if data_trnd:
            trnd_df_temp = pd.DataFrame([*data_trnd['results']], columns=trnd_columns)
            trnd_df = pd.concat([trnd_df, trnd_df_temp], ignore_index=True)
        else:
            break
except:
    print("Out of Pages")
    
    
# gathering current date
trnd_df['curr_date'] = datetime.date.today().strftime("%m-%d-%Y")
# converting to pandas datetime type 
trnd_df['curr_date'] = pd.to_datetime(trnd_df['curr_date'])
# printing out our results
trnd_df

<re.Match object; span=(12739, 12757), match='"total_pages":1000'>
Number: 1000

Exception ignored in: <finalize object at 0x1728c9ca0; dead>
Traceback (most recent call last):
  File "/Users/carterthurman/anaconda3/envs/Data/lib/python3.9/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/Users/carterthurman/anaconda3/envs/Data/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1181, in _close_pool_connections
    conn.close()
  File "/Users/carterthurman/anaconda3/envs/Data/lib/python3.9/site-packages/urllib3/connection.py", line 272, in close
    super().close()
KeyboardInterrupt:

Out of Pages
CPU times: user 2.2 s, sys: 127 ms, total: 2.33 s
Wall time: 11 s

,adult,backdrop_path,id,title,original_language,original_title,overview,poster_path,media_type,genre_ids,popularity,release_date,video,vote_average,vote_count,curr_date
0,False,/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg,753342,Napoleon,en,Napoleon,An epic that details the checkered rise and fa...,/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg,movie,"[36, 10752, 18]",1092.626,2023-11-22,False,6.445,1005,2024-01-12
1,False,/qgFrFXtiGfWN1zkk4sPd0nwFaBF.jpg,848187,Role Play,en,Role Play,Emma has a wonderful husband and two kids in t...,/7MhXiTmTl16LwXNPbWCmqxj7UxH.jpg,movie,"[28, 35, 10749]",26.680,2023-12-14,False,6.222,9,2024-01-12
2,False,/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg,955916,Lift,en,Lift,"An international heist crew, led by Cyrus Whit...",/paXvbaaT5kCZbCqiWrnf44tGAyn.jpg,movie,"[28, 35]",147.906,2024-01-10,False,7.200,5,2024-01-12
3,False,/uKP0B8HUJ08fas7NF77Xwu0bolJ.jpg,1214314,One More Shot,en,One More Shot,Following the attack on the black site in Pola...,/gdF3Q1Mcr2XvxLPStQSoQIO2cIj.jpg,movie,"[28, 53]",38.525,2024-01-12,False,7.306,18,2024-01-12
4,False,/rVJfabCz1ViynQCEz54MRqdZig1.jpg,1155089,Justice League: Crisis on Infinite Earths Part...,en,Justice League: Crisis on Infinite Earths Part...,Death is coming. Worse than death: oblivion. N...,/zR6C66EDklgTPLHRSmmMt5878MR.jpg,movie,"[16, 878, 28]",104.182,2024-01-09,False,7.900,53,2024-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,False,/A1Larywbw79kZQqkvCEiPHJqdLN.jpg,10494,Perfect Blue,ja,PERFECT BLUE,Pop singer Mima Kirigoe looks forward to a bri...,/6WTiOCfDPP8XV4jqfloiVWf7KHq.jpg,movie,"[16, 53]",62.429,1998-02-28,False,8.291,2283,2024-01-12
955,False,/aPvIX46VtxZDwu5bB2UcJ7xdpxs.jpg,977223,Polite Society,en,Polite Society,Martial artist-in-training Ria Khan believes s...,/lv1WqAo2ulQy9aSOG7ikR44p8RR.jpg,movie,"[35, 28, 18]",37.994,2023-04-27,False,6.380,118,2024-01-12
956,False,/3Nn5BOM1EVw1IYrv6MsbOS6N1Ol.jpg,162,Edward Scissorhands,en,Edward Scissorhands,A small suburban town receives a visit from a ...,/1RFIbuW9Z3eN9Oxw2KaQG5DfLmD.jpg,movie,"[14, 18, 10749]",57.406,1990-12-07,False,7.715,12284,2024-01-12
957,False,/1TecFmK3v6VJzsaGQgvrBiaypxW.jpg,1001500,The Starling Girl,en,The Starling Girl,17-year-old Jem Starling struggles with her pl...,/ysgnrkXwfFCxaBwviG2yNvzpfw5.jpg,movie,[18],13.415,2023-05-12,False,6.900,20,2024-01-12
958,False,/v6MVBFnQOscITvmAy5N5ras2JKZ.jpg,1924,Superman,en,Superman,Mild-mannered Clark Kent works as a reporter a...,/d7px1FQxW4tngdACVRsCSaZq0Xl.jpg,movie,"[878, 28, 12]",46.830,1978-12-14,False,7.121,3549,2024-01-12

In [21]:
# making trnd_movies.csv and showing schema
trnd_df.to_csv(trnd_dest)
! ls ../CSV
trnd_df.info()

final_movies.csv movies.csv       trnd_movies.csv  up_movies.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9995 entries, 0 to 9994
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              9995 non-null   bool
 1   backdrop_path      9626 non-null   object
 2   id                 9995 non-null   int64
 3   title              9995 non-null   object
 4   original_language  9995 non-null   object
 5   original_title     9995 non-null   object
 6   overview           9995 non-null   object
 7   poster_path        9937 non-null   object
 8   media_type         9995 non-null   object
 9   genre_ids          9995 non-null   object
 10  popularity         9995 non-null   float64
 11  release_date       9995 non-null   object
 12  video              9995 non-null   bool
 13  vote_average       9995 non-null   float64
 14  vote_count         9995 non-null   int64
 15  curr_date          9995 non-null   datetime64[ns]
dtypes: bool(2), datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 1.1+ MB

In [22]:
# 'append, replace, fail' arguments.
# index = False makes CSV not include index column
trnd_df.to_sql('trnd_movie_table', engine, if_exists='append', index=False)

995

### Upcoming Movies

In [40]:
# gathering Upcoming Movies

# specified page number
url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer {}".format(RA_KEY)
}

response_up = requests.get(url, headers=headers)

print(response_up)

<Response [200]>

#### API testing

In [10]:
# we want 'results'
# 'dates' is the day we got this info
# results are our results
# total pages is how many we can iterate through
print("Keys in Object: ", *data.keys(), "\nTotal Pages: ", str(data['total_pages']))

Keys in Object:  dates page results total_pages total_results
Total Pages:  49

In [13]:
# data of index one, keys and value
print(*data['results'][0].items())

('adult', False) ('backdrop_path', '/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg') ('genre_ids', [28, 12, 14]) ('id', 572802) ('original_language', 'en') ('original_title', 'Aquaman and the Lost Kingdom') ('overview', "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.") ('popularity', 1542.493) ('poster_path', '/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg') ('release_date', '2023-12-20') ('title', 'Aquaman and the Lost Kingdom') ('video', False) ('vote_average', 6.483) ('vote_count', 361)

In [120]:
for i in (data['results']):
    for clm, dta in i.items():
        print(clm, dta)

adult False
backdrop_path /xgGGinKRL8xeRkaAR9RMbtyk60y.jpg
genre_ids [16, 10751, 10402, 14, 35]
id 901362
original_language en
original_title Trolls Band Together
overview When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.
popularity 1620.617
poster_path /qV4fdXXUm5xNlEJ2jw7af3XxuQB.jpg
release_date 2023-10-12
title Trolls Band Together
video False
vote_average 7.1
vote_count 304
adult False
backdrop_path /yOm993lsJyPmBodlYjgpPwBjXP9.jpg
genre_ids [35, 10751, 14]
id 787699
original_language en
original_title Wonka
overview Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.
popularity 748.278
poster_path /qhb1qOilapbapxWQn9jtRCMwXJF.jpg
release_date 2023-12-06
title Wonka
video False
vote_average 6.906
vote_count 32
adult False
backdrop_path /bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg
genre_ids [18, 878, 28, 27]
id 940721
original_language ja
original_title ゴジラ-1.0
overview In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?
popularity 497.327
poster_path /fk62hm95sVNHy5Lkx3d18wj1v19.jpg
release_date 2023-11-03
title Godzilla Minus One
video False
vote_average 8.44
vote_count 67
adult False
backdrop_path /f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg
genre_ids [18, 36, 10752]
id 753342
original_language en
original_title Napoleon
overview An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.
popularity 375.702
poster_path /jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg
release_date 2023-11-22
title Napoleon
video False
vote_average 6.433
vote_count 611
adult False
backdrop_path /ehumsuIBbgAe1hg343oszCLrAfI.jpg
genre_ids [16, 10751, 14, 12]
id 1022796
original_language en
original_title Wish
overview Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.
popularity 293.457
poster_path /AcoVfiv1rrWOmAdpnAMnM56ki19.jpg
release_date 2023-11-13
title Wish
video False
vote_average 6.661
vote_count 93
adult False
backdrop_path /dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg
genre_ids [27, 53]
id 951491
original_language en
original_title Saw X
overview Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.
popularity 280.032
poster_path /aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg
release_date 2023-09-26
title Saw X
video False
vote_average 7.395
vote_count 1220
adult False
backdrop_path /lsJC9T6vo5HnqxEDjzGaczPUn6U.jpg
genre_ids [18, 35]
id 839369
original_language en
original_title May December
overview Twenty years after their notorious tabloid romance gripped the nation, a married couple buckles under pressure when an actress arrives to do research for a film about their past.
popularity 274.269
poster_path /yibtHDMO70RueiEmtrcJeTiiHFo.jpg
release_date 2023-11-16
title May December
video False
vote_average 6.585
vote_count 65
adult False
backdrop_path /zgQQF04u3OgNBJqClRNby1FPz9s.jpg
genre_ids [16, 10751, 28, 878, 35]
id 893723
original_language en
original_title PAW Patrol: The Mighty Movie
overview A magical meteor crash lands in Adventure City and gives the PAW Patrol pups superpowers, transforming them into The Mighty Pups.
popularity 270.828
poster_path /aTvePCU7exLepwg5hWySjwxojQK.jpg
release_date 2023-09-21
title PAW Patrol: The Mighty Movie
video False
vote_average 6.9
vote_count 185
adult False
backdrop_path /4kmNLwmVeT3xMciSRefE6SCi2hX.jpg
genre_ids [80, 18, 53]
id 1027073
original_language en
original_title In the Land of Saints and Sinners
overview In a remote Irish village, a damaged Finbar is forced to fight for redemption after a lifetime of sins, but what price is he willing to pay? In the land of saints and sinners, some sins can't be buried.
popularity 251.817
poster_path /443c0xNTLackGkFOKfbPClKMpIk.jpg
release_date 2023-10-06
title In the Land of Saints and Sinners
video False
vote_average 6.903
vote_count 36
adult False
backdrop_path /pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg
genre_ids [28, 18]
id 678512
original_language en
original_title Sound of Freedom
overview The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.
popularity 240.147
poster_path /qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg
release_date 2023-07-03
title Sound of Freedom
video False
vote_average 8.089
vote_count 1571
adult False
backdrop_path /bckxSN9ueOgm0gJpVJmPQrecWul.jpg
genre_ids [28, 12, 14]
id 572802
original_language en
original_title Aquaman and the Lost Kingdom
overview Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.
popularity 234.027
poster_path /8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg
release_date 2023-12-20
title Aquaman and the Lost Kingdom
video False
vote_average 0.0
vote_count 0
adult False
backdrop_path /ktHEdqmMWC1wdfPRMRCTZe2OISL.jpg
genre_ids [27, 53, 9648]
id 1071215
original_language en
original_title Thanksgiving
overview After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.
popularity 177.136
poster_path /f5f3TEVst1nHHyqgn7Z3tlwnBIH.jpg
release_date 2023-11-16
title Thanksgiving
video False
vote_average 6.355
vote_count 83
adult False
backdrop_path /iEFuHjqrE059SmflBva1JzDJutE.jpg
genre_ids [16, 10751, 14, 28, 10749, 10402]
id 496450
original_language fr
original_title Miraculous - le film
overview A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.
popularity 144.873
poster_path /dQNJ8SdCMn3zWwHzzQD2xrphR1X.jpg
release_date 2023-07-05
title Miraculous: Ladybug & Cat Noir, The Movie
video False
vote_average 7.787
vote_count 674
adult False
backdrop_path /ptz5ETMxDoRRiE69BVuIxJzyTEO.jpg
genre_ids [16, 35, 12, 10751]
id 940551
original_language en
original_title Migration
overview After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, via New York City, to tropical Jamaica.
popularity 132.642
poster_path /ldfCF9RhR40mppkzmftxapaHeTo.jpg
release_date 2023-12-06
title Migration
video False
vote_average 7.778
vote_count 9
adult False
backdrop_path /zZnsfR6BRqtxyLyAhsi2TMukEBx.jpg
genre_ids [16, 28, 80, 9648]
id 1047041
original_language ja
original_title 名探偵コナン 黒鉄の魚影（サブマリン）
overview Many engineers from around the world gather at the Interpol marine facility "Pacific Buoy" on Hachijo-jima, in the sea south of central Tokyo Prefecture coast, to witness the launch of a new system that connects all law enforcement camera systems around the world and enables facial recognition worldwide. Conan, along with his friends Kogoro, Ran, Agasa, Haibara, and the Detective Boys, also heads to the island with an invitation from Sonoko to see the whales. He receives a message from Subaru, who says that a Europol agent has been murdered in Germany by Gin. Perturbed, Conan sneaks onto the police ship led by Kuroda, which is bringing them to the island to protect the completion work, and tours the new facility, just in time for the Black Organization to kidnap a female engineer, seeking a piece of important data in her USB drive. A terrifying howl of screws is heard from the ocean as an unknown person approaches Haibara.
popularity 113.416
poster_path /ksQ8uNgoWsVH6a0oPB6zx08pOwU.jpg
release_date 2023-04-14
title Detective Conan: Black Iron Submarine
video False
vote_average 6.6
vote_count 53
adult False
backdrop_path /qElNES0sHVQcbzvGrTx7ccpGzij.jpg
genre_ids [878, 28, 18]
id 842675
original_language zh
original_title 流浪地球2
overview Humans built huge engines on the surface of the earth to find a new home. But the road to the universe is perilous. In order to save earth, young people once again have to step forward to start a race against time for life and death.
popularity 110.073
poster_path /pR858ihc6Ls9xohpdRJVjV787ml.jpg
release_date 2023-01-22
title The Wandering Earth II
video False
vote_average 7.2
vote_count 403
adult False
backdrop_path /H8YE8DDrnvr869RgCqLvhfcUFM.jpg
genre_ids [18]
id 970348
original_language en
original_title The Old Oak
overview A pub landlord in a previously thriving mining community struggles to hold onto his pub. Meanwhile, tensions rise in the town when Syrian refugees are placed in the empty houses in the community.
popularity 109.402
poster_path /xN293BKB0MDqpILmLCtGGYxQXKW.jpg
release_date 2023-09-29
title The Old Oak
video False
vote_average 7.415
vote_count 112
adult False
backdrop_path /A1g8AvP3KpDyu0iyjS6roRxK77v.jpg
genre_ids [53, 80]
id 978870
original_language it
original_title L'ultima notte di Amore
overview On the night before his retirement, police lieutenant Franco Amore is called to investigate the death of a long-time partner of his in a diamond heist in which he was involved.
popularity 98.993
poster_path /dBp0REsZkZ1HK1PycwlLdBtYdsd.jpg
release_date 2023-03-09
title Last Night of Amore
video False
vote_average 7.183
vote_count 304
adult False
backdrop_path /w1ZeZ8XYTBCovnXi9bwi7D7glM4.jpg
genre_ids [28, 80]
id 891699
original_language en
original_title Silent Night
overview A tormented father witnesses his young son die when caught in a gang's crossfire on Christmas Eve. While recovering from a wound that costs him his voice, he makes vengeance his life's mission and embarks on a punishing training regimen in order to avenge his son's death.
popularity 97.587
poster_path /tlcuhdNMKNGEVpGqBZrAaOOf1A6.jpg
release_date 2023-11-30
title Silent Night
video False
vote_average 6.942
vote_count 26
adult False
backdrop_path /sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg
genre_ids [35, 18]
id 840430
original_language en
original_title The Holdovers
overview A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break to babysit the handful of students with nowhere to go. Eventually, he forms an unlikely bond with one of them — a damaged, brainy troublemaker — and with the school’s head cook, who has just lost a son in Vietnam.
popularity 96.641
poster_path /VHSzNBTwxV8vh7wylo7O9CLdac.jpg
release_date 2023-10-27
title The Holdovers
video False
vote_average 7.768
vote_count 97

#### Python - SQL

In [44]:
%%time

# this section is to create the dataframe and gather the first 20 items

# gathering Upcoming Movies

# specified page number
url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer {}".format(RA_KEY)
}

response_up = requests.get(url, headers=headers)

print(response_up)

# decodes response into json object
json_data_up = response_up.content.decode()
# converts json object/string into python object
data_up = json.loads(json_data_up)

# making a list full of the column names
up_columns = [i for i in data_up['results'][0].keys()]
# unpacking data from json object into the data argument and setting columns, making a dataframe
up_df = pd.DataFrame([*data_up['results']], columns=up_columns)
up_df

<Response [200]>
CPU times: user 54.1 ms, sys: 4.93 ms, total: 59 ms
Wall time: 241 ms

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/yOm993lsJyPmBodlYjgpPwBjXP9.jpg,"[35, 10751, 14]",787699,en,Wonka,Willy Wonka – chock-full of ideas and determin...,654.778,/qhb1qOilapbapxWQn9jtRCMwXJF.jpg,2023-12-06,Wonka,False,7.100,934
1,False,/X8yF6STUk5Zr5nAuLBJiio8Sxh.jpg,"[18, 10749]",1143183,tl,Rewind,Mary loves John for as long as she can remembe...,466.285,/ru1i4ZR11lPPVArk3fOcO1VCOlD.jpg,2023-12-25,Rewind,False,7.059,17
2,False,/50stq3Jlny6oEgJjsXbQvbajCNw.jpg,"[10749, 18]",1020006,en,Priscilla,When teenage Priscilla Beaulieu meets Elvis Pr...,611.517,/uDCeELWWpsNq7ErM61Yuq70WAE9.jpg,2023-10-27,Priscilla,False,6.876,193
3,False,/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg,"[28, 53]",866398,en,The Beekeeper,One man’s campaign for vengeance takes on nati...,453.101,/A7EByudX0eOzlkQ2FIbogzyazm2.jpg,2024-01-10,The Beekeeper,False,7.500,20
4,False,/zX9m8h33pHXcES7ttO8v0ThiYj7.jpg,"[18, 28, 53]",1053592,es,Todos los nombres de Dios,"After being implicated in a terrorist attack, ...",373.468,/n15gfcgwV0LVPSobrayZcFHcwN6.jpg,2023-09-15,All the Names of God,False,7.048,42
5,False,/ptz5ETMxDoRRiE69BVuIxJzyTEO.jpg,"[16, 28, 12, 35, 10751]",940551,en,Migration,After a migrating duck family alights on their...,374.851,/ldfCF9RhR40mppkzmftxapaHeTo.jpg,2023-12-06,Migration,False,7.400,98
6,False,/vQpvNDc0AFao8BbWyXDFVVrqiZj.jpg,[27],853387,en,Lord of Misrule,When the daughter of the town's new priest goe...,326.801,/eCNJuGsCNdf2yf4F3UcDg1WZTbo.jpg,2023-10-26,Lord of Misrule,False,5.600,15
7,False,/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg,"[16, 28, 12, 878]",569094,en,Spider-Man: Across the Spider-Verse,"After reuniting with Gwen Stacy, Brooklyn’s fu...",326.690,/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg,2023-05-31,Spider-Man: Across the Spider-Verse,False,8.379,5466
8,False,/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg,"[28, 18]",678512,en,Sound of Freedom,"The story of Tim Ballard, a former US governme...",238.867,/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg,2023-07-03,Sound of Freedom,False,8.068,1764
9,False,/mgTeI8UNJzre7YMt24lfQLyXnA8.jpg,[18],1075175,en,How to Have Sex,Three British teenage girls go on a rites-of-p...,196.703,/rafwrzslLb203hQFIU8s0yRk0Qy.jpg,2023-11-02,How to Have Sex,False,6.520,101
10,False,/a0GM57AnJtNi7lMOCamniiyV10W.jpg,"[16, 12, 14]",508883,ja,君たちはどう生きるか,"While the Second World War rages, the teenage ...",208.361,/y9xS5NQTBnFjDoXhSFQeGxlmkoM.jpg,2023-07-14,The Boy and the Heron,False,7.390,628
11,False,/1PkBhxXdEejw8c5BC7T3cN7jz9g.jpg,"[35, 10749]",1072790,en,Anyone But You,"After an amazing first date, Bea and Ben’s fie...",194.025,/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg,2023-12-21,Anyone But You,False,7.400,53
12,False,/gsVC7HMf4VR2XFOyqjTSklY2Tms.jpg,"[878, 10749, 35]",792307,en,Poor Things,Brought back to life by an unorthodox scientis...,170.340,/jV3c2fsBNCJgcesxdNM9O0lwwdT.jpg,2023-11-21,Poor Things,False,8.041,86
13,False,/9ZlGiEKmcYrrxmiQEJDhjeT2kEW.jpg,"[28, 12, 10752]",1061181,ja,キングダム 運命の炎,To defend their kingdom against a sudden invas...,260.254,/60eYZkkksgKeeAV8fAAKQslZZnH.jpg,2023-07-28,Kingdom III: The Flame of Destiny,False,7.594,85
14,False,/cavK9ox37pxDg11RvJINMH63onU.jpg,"[27, 53]",744857,es,Cuando acecha la maldad,Residents of a small rural town discover that ...,174.966,/2gimJ06p9tVR4P6jacZWcLcNEwA.jpg,2023-10-05,When Evil Lurks,False,7.300,365
15,False,/m3s0jyPGtluJ48kD0fUiPjXrRhr.jpg,[35],673593,en,Mean Girls,New student Cady Heron is welcomed into the to...,202.390,/fbbj3viSUDEGT1fFFMNpHP1iUjw.jpg,2024-01-10,Mean Girls,False,7.300,17
16,False,/klb3yODwKMRle19EcvdeSatEZL7.jpg,"[27, 53]",1072342,en,Night Swim,Forced into early retirement by a degenerative...,158.385,/gSkfBGdxdialBMM7P02V4hcI6Ij.jpg,2024-01-03,Night Swim,False,5.300,33
17,False,None,"[18, 27]",1118824,tl,Mallari,"Inspired by true events, Mallari tells the hor...",109.563,/k11utHsPpfYdC5cr53TYe82ddV7.jpg,2023-12-25,Mallari,False,6.000,1
18,False,/kszooR7v1TLFM4pzx6IkKq2jDAN.jpg,"[18, 9648]",915935,fr,Anatomie d'une chute,"A woman is suspected of her husband’s murder, ...",123.257,/kQs6keheMwCxJxrzV83VUwFtHkB.jpg,2023-08-13,Anatomy of a Fall,False,7.729,586
19,False,/sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg,"[35, 18]",840430,en,The Holdovers,A curmudgeonly instructor at a New England pre...,123.842,/VHSzNBTwxV8vh7wylo7O9CLdac.jpg,2023-10-27,The Holdovers,False,7.659,330

In [45]:
%%time

# gathers the total pages of response
match = re.search(r'"total_pages":(\d+)', response_up.text)

# if the response gave a correct variable and not an error, it will grab the page number by the first group
# else, it will print "Number not found"
if match:
    page_number = match.group(1)
    print(f"Number: {page_number}")
else:
    print("Number not found")

# converting page_nunber into 'int' variable
page_number = int(page_number)
    
# gathering Upcoming Movies one page at a time through iteration
# this whole block of code with try to do it and until it fails, it will continue. 
# once it fails, it will print "Out of Pages"

# this block of code takes around 30 seconds to run.
try:
    # for each page starting at page 2 (because we already have page 1), iterate through and gather the response
    # including the url which the page_number is being formatted into, the headers with the environmental keys
    # and then putting it into a response variable which is then being decoded into a json object
    # and then loading into a data_trnd json object that can be searched through
    
    for page in range(2, page_number):
        # specified page number
        url = f"https://api.themoviedb.org/3/movie/upcoming?language=en-US&page={page}"
        headers = {
            "accept": "application/json",
            "Authorization": "Bearer {}".format(RA_KEY)
        }
        response_up = requests.get(url, headers=headers)
        # decodes response into json object
        json_data_up = response_up.content.decode()
        # converts json object/string into python object
        data_up = json.loads(json_data_up)
        # if data_up exists, then add it to a temporary dataframe with correct columns, and then 
        # join it (concat it) into the already created dataframe while ignoring the index column.
        if data_up:
            up_df_temp = pd.DataFrame([*data_up['results']], columns=up_columns)
            up_df = pd.concat([up_df, up_df_temp], ignore_index=True)
        else:
            break
except:
    print("Out of Pages")
    
    
# gathering current date
up_df['curr_date'] = datetime.date.today().strftime("%m-%d-%Y")
# converting to pandas datetime type 
up_df['curr_date'] = pd.to_datetime(up_df['curr_date'])
# printing out our results
up_df

Number: 53
CPU times: user 1.99 s, sys: 106 ms, total: 2.1 s
Wall time: 6.22 s

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,curr_date
0,False,/yOm993lsJyPmBodlYjgpPwBjXP9.jpg,"[35, 10751, 14]",787699,en,Wonka,Willy Wonka – chock-full of ideas and determin...,654.778,/qhb1qOilapbapxWQn9jtRCMwXJF.jpg,2023-12-06,Wonka,False,7.100,934,2024-01-12
1,False,/X8yF6STUk5Zr5nAuLBJiio8Sxh.jpg,"[18, 10749]",1143183,tl,Rewind,Mary loves John for as long as she can remembe...,466.285,/ru1i4ZR11lPPVArk3fOcO1VCOlD.jpg,2023-12-25,Rewind,False,7.059,17,2024-01-12
2,False,/50stq3Jlny6oEgJjsXbQvbajCNw.jpg,"[10749, 18]",1020006,en,Priscilla,When teenage Priscilla Beaulieu meets Elvis Pr...,611.517,/uDCeELWWpsNq7ErM61Yuq70WAE9.jpg,2023-10-27,Priscilla,False,6.876,193,2024-01-12
3,False,/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg,"[28, 53]",866398,en,The Beekeeper,One man’s campaign for vengeance takes on nati...,453.101,/A7EByudX0eOzlkQ2FIbogzyazm2.jpg,2024-01-10,The Beekeeper,False,7.500,20,2024-01-12
4,False,/zX9m8h33pHXcES7ttO8v0ThiYj7.jpg,"[18, 28, 53]",1053592,es,Todos los nombres de Dios,"After being implicated in a terrorist attack, ...",373.468,/n15gfcgwV0LVPSobrayZcFHcwN6.jpg,2023-09-15,All the Names of God,False,7.048,42,2024-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035,False,/2HwImzg3k1xYeUSjChpBW7MDBzs.jpg,[99],1229980,fr,"Iznik, les mystères de la basilique engloutie",,0.000,/fsSU6WYMyC1WqCyqenTxajQwZOB.jpg,2024-01-25,"Iznik, les mystères de la basilique engloutie",False,0.000,0,2024-01-12
1036,False,None,[35],1229913,es,El Roomie,Vivi is a young writer who is forced to find a...,0.000,/6NtvS6vFjQKpt8hnAk5D9Ig4trg.jpg,2024-01-18,El Roomie,False,0.000,0,2024-01-12
1037,False,None,[],1229838,sv,Barnen från Camp Ashraf,In the aftermath of the 1979 Iranian revolutio...,1.043,None,2024-01-31,The Children of Camp Ashraf,False,0.000,0,2024-01-12
1038,False,None,[],1229835,ku,Demo ke pelê gozan benî zer,"In southeastern Turkey, Kurds who want to live...",1.101,None,2024-01-30,When the Walnut Leaves Turn Yellow,False,0.000,0,2024-01-12
1039,False,None,[],1229831,sv,XXL,"Siblings Enzo and Magda have drifted apart, an...",1.322,None,2024-01-27,XXL,False,0.000,0,2024-01-12

In [46]:
# Cleaning Up

# Dropping unncessary columns
up_df.drop(columns=['genre_ids', 'video'], inplace=True)

# Changing datatypes
up_df['release_date'] = pd.to_datetime(up_df['release_date'])

# Reorganizing Columns
up_df = up_df[['original_title', 'id', 'overview', 
               'original_language', 'release_date', 'popularity', 'vote_average', 
               'vote_count', 'curr_date', 'backdrop_path', 'poster_path']]
up_df

,original_title,id,overview,original_language,release_date,popularity,vote_average,vote_count,curr_date,backdrop_path,poster_path
0,Wonka,787699,Willy Wonka – chock-full of ideas and determin...,en,2023-12-06,654.778,7.100,934,2024-01-12,/yOm993lsJyPmBodlYjgpPwBjXP9.jpg,/qhb1qOilapbapxWQn9jtRCMwXJF.jpg
1,Rewind,1143183,Mary loves John for as long as she can remembe...,tl,2023-12-25,466.285,7.059,17,2024-01-12,/X8yF6STUk5Zr5nAuLBJiio8Sxh.jpg,/ru1i4ZR11lPPVArk3fOcO1VCOlD.jpg
2,Priscilla,1020006,When teenage Priscilla Beaulieu meets Elvis Pr...,en,2023-10-27,611.517,6.876,193,2024-01-12,/50stq3Jlny6oEgJjsXbQvbajCNw.jpg,/uDCeELWWpsNq7ErM61Yuq70WAE9.jpg
3,The Beekeeper,866398,One man’s campaign for vengeance takes on nati...,en,2024-01-10,453.101,7.500,20,2024-01-12,/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg,/A7EByudX0eOzlkQ2FIbogzyazm2.jpg
4,Todos los nombres de Dios,1053592,"After being implicated in a terrorist attack, ...",es,2023-09-15,373.468,7.048,42,2024-01-12,/zX9m8h33pHXcES7ttO8v0ThiYj7.jpg,/n15gfcgwV0LVPSobrayZcFHcwN6.jpg
...,...,...,...,...,...,...,...,...,...,...,...
1035,"Iznik, les mystères de la basilique engloutie",1229980,,fr,2024-01-25,0.000,0.000,0,2024-01-12,/2HwImzg3k1xYeUSjChpBW7MDBzs.jpg,/fsSU6WYMyC1WqCyqenTxajQwZOB.jpg
1036,El Roomie,1229913,Vivi is a young writer who is forced to find a...,es,2024-01-18,0.000,0.000,0,2024-01-12,None,/6NtvS6vFjQKpt8hnAk5D9Ig4trg.jpg
1037,Barnen från Camp Ashraf,1229838,In the aftermath of the 1979 Iranian revolutio...,sv,2024-01-31,1.043,0.000,0,2024-01-12,None,None
1038,Demo ke pelê gozan benî zer,1229835,"In southeastern Turkey, Kurds who want to live...",ku,2024-01-30,1.101,0.000,0,2024-01-12,None,None
1039,XXL,1229831,"Siblings Enzo and Magda have drifted apart, an...",sv,2024-01-27,1.322,0.000,0,2024-01-12,None,None

In [49]:
up_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   original_title     1040 non-null   object
 1   id                 1040 non-null   int64
 2   overview           1040 non-null   object
 3   original_language  1040 non-null   object
 4   release_date       1037 non-null   datetime64[ns]
 5   popularity         1040 non-null   float64
 6   vote_average       1040 non-null   float64
 7   vote_count         1040 non-null   int64
 8   curr_date          1040 non-null   datetime64[ns]
 9   backdrop_path      542 non-null    object
 10  poster_path        787 non-null    object
dtypes: datetime64[ns](2), float64(2), int64(2), object(5)
memory usage: 89.5+ KB

In [ ]:
# converting to csv file
up_df.to_csv(up_dest)
# 'append, replace, fail' arguments.
# index = False makes CSV not include index column
up_df.to_sql('up_movie_table', engine, if_exists='replace', index=False)